project:
  type: website

website:
  title: "StatPan"
  site-url: https://statpan.com
  description: "AI & Data Infra, For Agents"
  google-analytics: "G-T89ZMSEYS4"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/StatPan
        aria-label: GitHub
  page-footer:
    center: |
      &copy; 2026 StatPan. All rights reserved.

format:
  html:
    theme:
      light: [flatly, custom.scss]
    css: styles.css
    toc: true
